# Configure this sonar
[sonar]
mode            = bathy             # See mode.operation_modes
sidescanMode    = snippets          # See mode.sidescan_modes
flipMode        = bathy             #
gateMode        = depth             # See mode.range_modes
gateTilt        = 0                 # [deg]
autogatePreset  = normal            # Adaptive gate mode, see mode.adaptive_gate_modes

[range]
gate_mode_range  = 0 50         # Range for gate mode "range" 
gate_mode_depth  = 0 50         # Range for gate mode "depth"

[swath]
direction       = 0             # [deg] [-90, 90]
openingAngle    = 140           # [deg] [0, 360]
resolution      = 256 128       # [VRES 64-2048, HRES 64-512]
mfDecimation    = 1             # [1, 16] Decimation factor before matched filter

[tx]
frequency       = 400           # [200, 700] kHz MBES
bandwidth       = 80            # [0, 80] kHz
amplitude       = 15            # [0, 15]
length          = 500           # [10, 819] microseconds
gain            = 0             # [0, 100] dB, VGA ramp must be 0 for this to work.
vga             = 50            # VGA ramp in dB/100 m
rate            = -1            # [-1, 60] Max allowable pingrate
tpRate          = 5             # [-1, 60] Water column output rate
snippetRate     = 18            # [-1, 60] Snippet output rate
triggerMode     = externalRisingEdge      # See mode.trigger_modes

[environment]
soundVelocity   = -1                # Sets fixed sound velocity (-1 to use ext. probe)
timeSource      = ntp               # See modes.time_source_modes
ntpServer       = 192.168.1.91      # Server IP


### DO NOT CHANGE MODE VALUES ###
[mode.time_source_modes]
irig_b              = 0         #
ntp                 = 1         #
irig_b_inverted     = 2         #
ntp_pps_positive    = 3         #
ntp_pps_negative    = 4         #
zda_pps_positive    = 5         #
zda_pps_negative    = 6         #
zda                 = 7         #
free_run            = 8         # Time since boot

# Definitions
[mode.operation_modes]
forward = 0         #
bathy = 1           #
bathyAmp = 2        #
bfPassThrough = 4   #
edgeEnhance = 5     #
superRes = 6        #
multiDetect = 7     #

[mode.sidescan_modes]
snippets = 0        #
sidescan = 1        #
croppedSidescan = 9 #

[mode.flip_modes]
fls = 0     # Sonar projector upwards
bathy = 1   # Sonar projector towards stern

[mode.gate_modes]
range = 0 # Gate by range
depth = 1 # Gate by depth
mixed = 2 # Gate by range and depth

[mode.adaptive_gate_modes]
off = 0
wide = 1
normal = 2
narrow = 3

[mode.trigger_modes]
fixedRate = 0                   #
fixedRateTimeSync = 1           #
fullRange = 2                   # Max allowed by set range
adaptive = 3                    # Max allowed by measured range
externalRisingEdge = 4          # External trigger (rising edge)
externalFallingEdge = 5         # External trigger (falling edge)




